name: Testcontainers
on: [push]
jobs:
  test:
    runs-on: [ubuntu-latest]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: toto
          POSTGRES_USERNAME: toto
          POSTGRES_PORT: 5432
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Setup with Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew test
