name: Testcontainers
on: [push]
jobs:
  test:
    runs-on: [ubuntu-latest]
    env:
      ACTIONS_RUNNER_PRINT_LOG_TO_STDOUT: true
    services:
      postgres:
        image: postgres:16.1
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USERNAME: postgres
          PGUSER: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DB: sample
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Setup with Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew clean test
